import { useState } from 'react';
import { Link, NavLink, Route, Routes } from 'react-router-dom';
import { ArrowDown, ArrowLeft, ArrowRight, Check, ChevronRight, Compass, Diamond, Expand, Feather, Gamepad2, Leaf, LockKeyhole, Mountain, Play, Settings2, Sparkles, X } from 'lucide-react';
import { PROJECT, WORLDS } from '../config/project';
import { GameCanvas } from '../components/GameCanvas';
import { Modal } from '../components/Modal';
import { loadPreferences, savePreferences, type Preferences } from '../services/preferences';

type Dialog = 'settings' | 'controls' | 'credits' | null;
export function App() {
  const [dialog, setDialog] = useState<Dialog>(null);
  const [preferences, setPreferences] = useState(loadPreferences);
  const [saveError, setSaveError] = useState(false);
  function updatePreferences(next: Preferences) { setPreferences(next); setSaveError(!savePreferences(next)); }
  return <div className={`app ${preferences.reducedMotion ? 'reduced-motion' : ''} ${preferences.highContrast ? 'high-contrast' : ''}`}>
    <header className="site-header"><Link to="/" className="brand" aria-label={`${PROJECT.name} home`}><span className="brand-mark"><Diamond size={24} strokeWidth={1.6} /></span><span>SKYBOUND<span className="brand-sub">A D V E N T U R E</span></span></Link>
      <nav aria-label="Main navigation"><NavLink to="/" end>The adventure</NavLink><NavLink to="/worlds">Discover the worlds</NavLink><button onClick={() => setDialog('controls')}>How to play <ArrowRight size={13} /></button></nav>
      <button className="icon-button settings-button" onClick={() => setDialog('settings')} aria-label="Open settings"><Settings2 size={20} /></button>
    </header>
    <Routes>
      <Route path="/" element={<Landing openDialog={setDialog} />} />
      <Route path="/worlds" element={<Worlds />} />
      <Route path="/practice" element={<GamePage practice preferences={preferences} active={dialog === null} openDialog={setDialog} />} />
      <Route path="/play" element={<GamePage preferences={preferences} active={dialog === null} openDialog={setDialog} />} />
      <Route path="*" element={<main className="inner-page"><h1>A path yet to be discovered.</h1><Link className="primary-button" to="/">Return home <ArrowRight size={18} /></Link></main>} />
    </Routes>
    <footer className="site-footer"><span><span className="live-dot" /> A LITTLE EXPLORER. A LIMITLESS SKY.</span><button onClick={() => setDialog('credits')}>Made for the wonder of it <Sparkles size={13} /></button><span>STAGE 03 <span className="footer-divider">/</span> v{PROJECT.version}</span></footer>
    {dialog && <Modal onClose={() => setDialog(null)}><button autoFocus className="icon-button modal-close" onClick={() => setDialog(null)} aria-label="Close dialog"><X size={20} /></button><span className="eyebrow">MAKE YOURSELF AT HOME</span><h2 id="dialog-title">{dialog === 'settings' ? 'Your kind of adventure.' : dialog === 'controls' ? 'A few small steps.' : 'A world of our own.'}</h2>
      {dialog === 'settings' && <><p>Display preferences are saved on this device.</p><label className="toggle-row"><span>Reduced motion<small>Turn off drifting scenery and particles</small></span><input type="checkbox" checked={preferences.reducedMotion} onChange={event => updatePreferences({ ...preferences, reducedMotion: event.target.checked })} /></label><label className="toggle-row"><span>High contrast UI<small>Stronger backgrounds and text contrast</small></span><input type="checkbox" checked={preferences.highContrast} onChange={event => updatePreferences({ ...preferences, highContrast: event.target.checked })} /></label>{saveError && <p role="alert">Your browser blocked storage. Preferences apply for this visit.</p>}<p className="note">Audio, difficulty, and control remapping arrive with their gameplay systems.</p></>}
      {dialog === 'controls' && <><p>The Verdant Trail is ready. Click the scene to focus, then try these controls.</p><div className="controls-list">{[['A / D or ← / →', 'Move'], ['Space / W / ↑', 'Jump'], ['Shift', 'Sprint'], ['R', 'Return to start'], ['Esc', 'Pause / resume']].map(([key, action]) => <div key={action}><span>{action}</span><kbd>{key}</kbd></div>)}</div><p className="note">Touch devices also have move, sprint, and jump buttons. Crouching, combat, interactions, and gamepad mapping arrive with later systems.</p></>}
      {dialog === 'credits' && <><p>Meet Ari, a young explorer following the last light of the scattered sky crystals. Six floating kingdoms. Countless hidden paths. One extraordinary journey.</p><div className="credit-card"><Leaf size={24} /><span>Original world, character & illustration<small>Created specifically for {PROJECT.name}.</small></span></div><p className="note">Built with React, TypeScript, Vite, Phaser 3, and Lucide icons. No third-party game artwork or music.</p><a className="text-link" href="https://phaser.io" target="_blank" rel="noreferrer">Powered by Phaser <ArrowRight size={15} /></a></>}
    </Modal>}
  </div>;
}

function Landing({ openDialog }: { openDialog: (dialog: Dialog) => void }) {
  return <main className="landing"><section className="hero"><div className="landscape" aria-hidden="true" /><div className="hero-shade" /><div className="floating-specks" aria-hidden="true"><i /><i /><i /><i /><i /></div>
    <div className="hero-content"><div className="pill"><span className="live-dot" /> A NEW ADVENTURE IS ON THE HORIZON</div><h1>SKYBOUND<span>ADVENTURE</span></h1><div className="title-ornament"><span /><Diamond size={11} /><span /></div><h2>Explore. Discover. <em>Rise Beyond the Clouds.</em></h2><p className="hero-description">Beyond the clouds, a forgotten world is waiting.<br />Follow Ari into floating kingdoms, uncover hidden<br className="desktop-break" /> wonders, and bring the light back home.</p>
    <div className="hero-actions"><Link to="/play" className="primary-button"><Play size={16} fill="currentColor" /> PLAY NOW <ArrowRight size={19} /></Link><button className="secondary-button" onClick={() => openDialog('controls')}><Gamepad2 size={19} /> How to play</button></div>
    <div className="play-note"><span className="tiny-diamond">◆</span> Free to explore <span>·</span> No download needed</div><p className="stage-note">The Verdant Trail / Explore the world preview</p>
    </div><div className="scene-caption"><span className="caption-line" /><span>01 / EMERALD VALLEY<small>Every great journey starts with a little wonder.</small></span><Compass size={28} strokeWidth={1} /></div><button onClick={() => document.getElementById('discover')?.scrollIntoView({ behavior: 'smooth' })} className="scroll-hint"><ArrowDown size={15} /> THERE’S A WORLD UP THERE</button>
  </section>
  <section id="discover" className="discovery"><div className="discovery-heading"><div><span className="eyebrow">FOLLOW YOUR CURIOSITY</span><h2>A little courage goes a long way.</h2></div><Link className="text-link" to="/worlds">Discover the worlds <ArrowRight size={17} /></Link></div><div className="feature-grid"><Feature icon={<Mountain />} number="01" title="Six worlds. Endless wonder." text="From emerald treetops to the edge of the sky. Every kingdom holds a new story." /><Feature icon={<Diamond />} number="02" title="For the curious at heart." text="Follow the glimmer. Find a hidden path. Some treasures are worth the detour." /><Feature icon={<Feather />} number="03" title="Find your own way to fly." text="A small explorer with a big heart. An adventure that grows with every leap." /></div></section>
  </main>;
}
function Feature({ icon, number, title, text }: { icon: React.ReactNode; number: string; title: string; text: string }) { return <article className="feature"><div className="feature-top"><span className="feature-icon">{icon}</span><span>{number}</span></div><h3>{title}</h3><p>{text}</p></article>; }
function Worlds() { return <main className="inner-page worlds-page"><Link className="text-link" to="/"><ArrowLeft size={16} /> Back to the adventure</Link><span className="eyebrow">THE WORLD BEYOND YOUR WINDOW</span><h1>Six kingdoms. One sky.</h1><p>A glimpse of the journey ahead. Stages and progression will unlock in later milestones.</p><div className="world-grid">{WORLDS.map((world, index) => <article className={`world-card world-${index}`} key={world.name} style={{ '--world-color': world.color } as React.CSSProperties}><span className="world-number">WORLD 0{index + 1}</span><div className="world-symbol">{index === 0 ? <Leaf size={46} strokeWidth={1} /> : <Mountain size={46} strokeWidth={1} />}</div><h2>{world.name}</h2><p>{world.label}</p>{index === 0 ? <Link to="/play" className="text-link">Explore the Verdant Trail <ChevronRight size={17} /></Link> : <span className="locked"><LockKeyhole size={13} /> Coming in a future world</span>}</article>)}</div></main>; }
function GamePage({ preferences, active, openDialog, practice = false }: { preferences: Preferences; active: boolean; practice?: boolean; openDialog: (dialog: Dialog) => void }) {
  const [fullscreenError, setFullscreenError] = useState(false);
  async function fullscreen() { try { if (document.fullscreenElement) await document.exitFullscreen(); else await document.querySelector('.game-frame')?.requestFullscreen(); } catch { setFullscreenError(true); } }
  return <main className="inner-page play-page"><div className="play-heading"><Link to="/" className="text-link"><ArrowLeft size={17} /> Back to the adventure</Link><span className="eyebrow">YOUR FIRST LOOK BEYOND THE CLOUDS</span><div><button className="icon-button" onClick={() => openDialog('settings')} aria-label="Scene settings"><Settings2 size={18} /></button><button className="icon-button" onClick={fullscreen} aria-label="Toggle fullscreen"><Expand size={18} /></button></div></div><GameCanvas key={practice ? 'practice' : '1-1'} course={practice ? 'practice' : '1-1'} reducedMotion={preferences.reducedMotion} active={active} /><div className="preview-info"><div><span className="pill"><Check size={13} /> {practice ? 'MOVEMENT PRACTICE' : 'WORLD 1 / TERRAIN PREVIEW'}</span><h1>{practice ? 'A little room to practice.' : 'Welcome to the Verdant Trail.'}</h1><p>{practice ? 'The original safe course, with the same responsive controls. Hold jump to soar; tap for a short hop.' : 'Follow the meadow, take the high road, or find the path through Mossroot Hollow. A missed leap returns you to the start.'}</p><Link className="text-link" to={practice ? '/play' : '/practice'}>{practice ? 'Explore the Verdant Trail' : 'Return to movement practice'} <ArrowRight size={15} /></Link>{fullscreenError && <p role="alert">Fullscreen is unavailable in this browser.</p>}</div><Link to="/worlds" className="secondary-button"><Compass size={18} /> Explore the worlds <ArrowRight size={17} /></Link></div></main>;
}

