import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await mkdir('artifacts', { recursive: true });
try {
  await page.goto('http://127.0.0.1:5173', { waitUntil: 'networkidle' });
  await page.screenshot({ path: 'artifacts/landing-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Open settings' }).click();
  await page.keyboard.press('Shift+Tab');
  assert.equal(await page.evaluate(() => document.activeElement?.closest('dialog') !== null), true);
  await page.getByRole('checkbox', { name: /Reduced motion/ }).check();
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await page.reload();
  await page.getByRole('button', { name: 'Open settings' }).click();
  assert.equal(await page.getByRole('checkbox', { name: /Reduced motion/ }).isChecked(), true);
  await page.getByLabel('Master volume').press('End');
  assert.equal(await page.getByLabel('Master volume').inputValue(), '1');
  await page.keyboard.press('Escape');
  await page.getByRole('link', { name: 'PLAY NOW' }).click();
  await page.getByText('1-1 / The Verdant Trail').waitFor();
  assert.equal(await page.locator('canvas').count(), 1);
  await page.screenshot({ path: 'artifacts/scene-desktop.png', fullPage: true });
  await page.getByRole('link', { name: 'Explore the worlds' }).click();
  await expect(page.locator('.stage-stop')).toHaveCount(4);
  await expect(page.locator('.world-card')).toHaveCount(5);
  await page.screenshot({ path: 'artifacts/stage8-world-map.png', fullPage: true });
  await page.getByRole('link', { name: /Play 1-1: Verdant Trail/ }).click();
  await page.getByText('1-1 / The Verdant Trail').waitFor();
  assert.equal(await page.locator('canvas').count(), 1);
  await page.goto('http://127.0.0.1:5173/#/worlds');
  await page.evaluate(() => localStorage.setItem('skybound.save.v1', JSON.stringify({ version: 1, totalScore: 5000, levels: { '1-1': { completed: true, completions: 1, bestScore: 5000, bestTimeMs: 90000, gems: 2, totalGems: 3 } } })));
  await page.reload();
  await page.getByRole('link', { name: /Play 1-2: Moonlit Grove/ }).click();
  await page.getByText('1-2 / Moonlit Grove').waitFor();
  assert.equal(await page.locator('canvas').count(), 1);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'artifacts/scene-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.getByRole('link', { name: 'Back to the adventure' }).click();
  await page.getByRole('button', { name: 'Open settings' }).click();
  await page.getByRole('checkbox', { name: /Reduced motion/ }).uncheck();
  await page.getByRole('checkbox', { name: /High contrast UI/ }).check();
  await page.keyboard.press('Escape');
  await page.getByRole('link', { name: 'PLAY NOW' }).click();
  await page.getByText('1-1 / The Verdant Trail').waitFor();
  await page.getByRole('link', { name: 'Back to the adventure' }).click();
  await page.getByRole('button', { name: 'Open settings' }).click();
  await page.getByRole('checkbox', { name: /High contrast UI/ }).uncheck();
  await page.keyboard.press('Escape');
  await page.screenshot({ path: 'artifacts/landing-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.deepEqual(errors, []);
  const touch = await browser.newContext({ viewport: { width: 844, height: 390 }, hasTouch: true, isMobile: true });
  const touchPage = await touch.newPage();
  await touchPage.goto('http://127.0.0.1:5173');
  await touchPage.getByRole('link', { name: 'PLAY NOW' }).tap();
  await touchPage.getByText('1-1 / The Verdant Trail').waitFor();
  assert.equal(await touchPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await touch.close();
  console.log('Browser checks passed: preferences persist, navigation, Phaser loading/rendering, scene cleanup, mobile layout, no runtime errors.');
} finally { await browser.close(); }
